language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.0" TENANT_SCHEMAS="django-tenant-schemas<1.9.0"
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.0" TENANT_SCHEMAS="django-tenant-schemas"
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.1" TENANT_SCHEMAS="django-tenant-schemas<1.9.0"
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.1" TENANT_SCHEMAS="django-tenant-schemas"
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.2" TENANT_SCHEMAS="django-tenant-schemas<1.9.0"
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.2" TENANT_SCHEMAS="django-tenant-schemas"
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.3" TENANT_SCHEMAS="django-tenant-schemas<1.9.0"
  - DJANGO_SPEC="<1.12" CELERY_SPEC="<4.3" TENANT_SCHEMAS="django-tenant-schemas"
  - DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenant-schemas<1.9.0"
  - DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenant-schemas"
  - DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenants<2.1.0"
  - DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenants"

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenants<2.1.0"
  - python: "2.7"
    env: DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenants"

install:
  - "pip install \"Django${DJANGO_SPEC}\" \"celery${CELERY_SPEC}\" \"${TENANT_SCHEMAS}\""
  - pip install -r requirements.txt -e .

services:
  - postgresql
  - rabbitmq

addons:
  postgresql: "9.5"

sudo: required

before_script:
  - psql -c "create user tenant_celery with password 'qwe123'" -U postgres
  - psql -c "alter role tenant_celery createdb" -U postgres

script: "./run-tests"
