language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

dist: trusty

env:
  - DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenant-schemas"
  - DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenants"

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_SPEC= CELERY_SPEC= TENANT_SCHEMAS="django-tenants"

install:
  - "pip install \"Django${DJANGO_SPEC}\" \"celery${CELERY_SPEC}\" \"${TENANT_SCHEMAS}\""
  - pip install -r requirements.txt -e .

services:
  - postgresql
  - rabbitmq

addons:
  postgresql: "9.5"

sudo: required

before_script:
  - psql -c "create user tenant_celery with password 'qwe123'" -U postgres
  - psql -c "alter role tenant_celery createdb" -U postgres
  - psql -c "create database tenant_celery with owner tenant_celery" -U postgres

script: "./run-tests"
