language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_LT=1.12 CELERY_LT=4.0
  - DJANGO_LT=1.12 CELERY_LT=4.1
  - DJANGO_LT=1.12 CELERY_LT=4.2
  - DJANGO_LT=1.12 CELERY_LT=4.3

install:
  - "pip install \"Django<${DJANGO_LT}\" \"celery<${CELERY_LT}\""
  - pip install .

services:
  - postgresql

addons:
  postgresql: "9.5"

sudo: required

before_script:
  - psql -c "create user tenant_celery with password 'qwe123'" -U postgres
  - psql -c "alter role tenant_celery createdb" -U postgres

script: "cd test_app && python manage.py test tenant_schemas_celery"
